# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


# jobs:
#   call-workflow-passing-data:
#     uses: musset0/test_actions_02/.github/workflows/resuable_workflow_job_public.yml@v1.2.3
#     with:
#       who-to-greet: 'mussett'
#     secrets:
#       AWS: '123'

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    outputs:
      mod_id: ${{steps.mod_id.outputs.time}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: run mod_id
        id: mod_id
        uses: dreamli0/my-action@main
        with:
          hi-there: 'one'

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!
         
      - name: run
        uses: musset0/my-action@main
        with:
          who-to-greet: 'worldc'
      - run: echo "${{steps.mod_id.outputs.time}}"
        

  output:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - run: echo "${{needs.build.outputs.mod_id}} version "
      

      
     
       
